apiVersion: v1
kind: Service
metadata:
  name: postgres1-service
  namespace: tp2
  labels:
    app: postgres1
spec:
  ports:
  - port: 5432
    name: postgres1
  type: ClusterIP
  selector:
    app: postgres1