apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro1
  namespace: tp2
spec:
  selector:
    matchLabels:
      app: micro1
  template:
    metadata:
      labels:
        app: micro1
    spec:
      containers:
      - name: micro1
        image: allaismail/microservice1_nom_prenom
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_IP
          value: postgres1-service
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: micro1_db
        ports:
        - containerPort: 8001

