apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast1
spec:
  selector:
    matchLabels:
      app: fast1
  template:
    metadata:
      labels:
        app: fast1
    spec:
      containers:
      - name: fast1
        image: allaismail/backend
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_IP
          value: "10.152.183.230" 
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: fastapi_database
        ports:
        - containerPort: 8000

